name: Deploy

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: []
    environment: ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: ./publish
    
    - name: Deploy to Staging
      if: github.ref == 'refs/heads/dev' || github.event.inputs.environment == 'staging'
      run: |
        echo "Deploying to staging environment..."
        # Add your staging deployment commands here
        # Example: az webapp deployment source config-zip --resource-group myResourceGroup --name myApp --src ./publish.zip
    
    - name: Deploy to Production
      if: github.ref == 'refs/heads/master' || github.event.inputs.environment == 'production'
      run: |
        echo "Deploying to production environment..."
        # Add your production deployment commands here
        # Example: az webapp deployment source config-zip --resource-group myResourceGroup --name myApp --src ./publish.zip
    
    - name: Notify deployment status
      run: |
        echo "Deployment completed successfully!"
        echo "Environment: ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}"
        echo "Commit: ${{ github.sha }}"